#!/bin/bash

# --- Environment Setup ---
echo "Activating conda environment..."
conda activate ~/env/lth_env/
echo "Loaded CUDA and GCC modules..."
module load cuda/11.1.1_gcc-9.3.0
module load gcc/9.3.0
rm ~/*pbs*

# --- Move to script directory ---
cd ~/LTH/manuscript/Tranfer/ || {
    echo "Failed to change directory to ~/LTH/manuscript/Tranfer/"
    exit 1
}
# get variables

echo "MODEL: $MODEL"
echo "DATASET: $DATASET"
echo "EPOCHS: $EPOCHS"
echo "BREAK_GROUP: $BREAK_GROUP"

OUTPUT_FILE="output_${MODEL}_${DATASET}_epochs${EPOCHS}_break${BREAK_GROUP}.txt"
echo "Output will be saved to: $OUTPUT_FILE"

python main_1.py --model "$MODEL" --dataset "$DATASET" --pretrain "$EPOCHS" --break_group "$BREAK_GROUP" > "$OUTPUT_FILE" 2>&1