#!/bin/bash

# --- Input Validation ---
if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
    echo "Usage: $0 <discovery_epochs> <hpc_compute_epochs> [mode]"
    echo "  mode: 'all' (default) or 'subset' (runs ONLY Control_Continuted and Dynamic_Region_All_Combined)"
    echo "Example: $0 50 100 subset"
    exit 1
fi

EPOCHS=$1
PRETRAIN=$2
MODE=${3:-all} # Defaults to 'all' if no 3rd argument is provided

models=("MobileNet")
#models=("ConvNeXt" "MobileNet" "InceptionNet" "XceptionNet" "RegNetX_400MF" "VGG16")
datasets=("tinyimagenet" "Cifar10" "Cifar100")
quant=("False" "True")

echo "=== Submitting Stage 2: Parallel HPC Execution ==="
echo "    Discovery Budget (Epochs): $EPOCHS | HPC Target (Pretrain): $PRETRAIN | Mode: $MODE"

for model in "${models[@]}"; do
    for dataset in "${datasets[@]}"; do
        for flag in "JF"; do
            
            # Locate the JSON file created by Stage 1 
            json_file="${model}_${dataset}_epochs${EPOCHS}_pretrain${PRETRAIN}_${flag}_discovered_regions.json"
            
            if [ ! -f "$json_file" ]; then
                echo "[WARN] Waiting for $json_file to be generated by Stage 1... Skipping."
                continue
            fi

            # Read the dynamic experiment names out of the JSON file directly (will inherently include 'Control')
            mapfile -t dynamic_experiments < <(python -c "import json; print('\n'.join(json.load(open('$json_file')).keys()))")

            for quant_flag in "${quant[@]}"; do
                for experiment in "${dynamic_experiments[@]}"; do
                    
                    # --- Mode Filtering Logic ---
                    if [ "$MODE" = "subset" ]; then
                        if [[ "$experiment" != "Control_Continuted" && "$experiment" != "Dynamic_Region_All_Combined" ]]; then
                            # Skip this iteration if it's not one of our target subset experiments
                            continue
                        fi
                    fi
                    
                    # Fire off the true parallel compute jobs
                    command="qsub -q all.q -l ngpus=1 -v MODEL=\"$model\",DATASET=\"$dataset\",EXPERIMENT=\"$experiment\",FLAG=\"$flag\",QUANT=\"$quant_flag\",EPOCHS=\"$EPOCHS\",PRETRAIN=\"$PRETRAIN\" submit_job.pbs"
                    
                    echo "Executing: $command"
                    eval "$command"
                    
                done
            done

        done
    done
done
