#!/bin/bash

# --- Input Validation ---
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <discovery_epochs> <hpc_compute_epochs>"
    echo "Example: $0 50 100"
    exit 1
fi

EPOCHS=$1
PRETRAIN=$2

models=("VGG16" "RegNetX_400MF" "XceptionNet" "InceptionNet" "MobileNet" "ConvNeXt")
datasets=("tinyimagenet" "Cifar10" "Cifar100")
quant=("True" "False")

echo "=== Submitting Stage 2: Parallel HPC Execution ==="
echo "    Discovery Budget (Epochs): $EPOCHS | HPC Target (Pretrain): $PRETRAIN"

for model in "${models[@]}"; do
    for dataset in "${datasets[@]}"; do
        for flag in "JF"; do
            
            # Locate the JSON file created by Stage 1 
            json_file="${model}_${dataset}_epochs${EPOCHS}_pretrain${PRETRAIN}_${flag}_discovered_regions.json"
            
            if [ ! -f "$json_file" ]; then
                echo "[WARN] Waiting for $json_file to be generated by Stage 1... Skipping."
                continue
            fi

            # Read the dynamic experiment names out of the JSON file directly (will inherently include 'Control')
            mapfile -t dynamic_experiments < <(python -c "import json; print('\n'.join(json.load(open('$json_file')).keys()))")

            for quant_flag in "${quant[@]}"; do
                for experiment in "${dynamic_experiments[@]}"; do
                    
                    # Fire off the true parallel compute jobs
                    command="qsub -q all.q -l ngpus=1 -v MODEL=\"$model\",DATASET=\"$dataset\",EXPERIMENT=\"$experiment\",FLAG=\"$flag\",QUANT=\"$quant_flag\",EPOCHS=\"$EPOCHS\",PRETRAIN=\"$PRETRAIN\" submit_job.pbs"
                    
                    echo "Executing: $command"
                    eval "$command"
                    
                done
            done

        done
    done
done
