#!/bin/bash
#PBS -N prune_${MODEL}_${DATASET}       # Job name (dynamically set based on model and dataset)
#PBS -l walltime=12:00:00               # Max walltime (12 hours, adjust as needed)
#PBS -l ngpus=1            # Number of nodes, processors per node, and 1 GPU
#PBS -o logs/${MODEL}_${DATASET}_output.txt  # Output file for job logs
#PBS -e logs/${MODEL}_${DATASET}_error.txt   # Error file for job logs
#PBS -V                                 # Export environment variables

# Activate the conda environment
conda activate ~/env/lth_env/
module load cuda/11.1.1_gcc-9.3.0
module load gcc/9.3.0
rm submit_job.*
# Change to the directory where qsub was called
cd /Users/jgafur/LTH/manuscript/structured_study

# Run the Python script with the parameters
time ~/env/lth_env/bin/python  main_experiment.py \
  --model ${MODEL} \
  --dataset ${DATASET} \
  --steps 21 \
  --device cuda \
  --strategy magnitude \
  --finetune_epochs 30 \
  --pretrain_epochs 10 \
  --batch_size 128

time ~/env/lth_env/bin/python  main_experiment.py \
  --model ${MODEL} \
  --dataset ${DATASET} \
  --steps 21 \
  --device cuda \
  --strategy magnitude \
  --finetune_epochs 30 \
  --pretrain_epochs 10 \
  --batch_size 128